language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - nightly
services: docker

notifications:
  email: false

after_success:
  - julia --project=coverage/ -e 'using Pkg; Pkg.instantiate()'
  - julia --project=coverage/ coverage/coverage.jl

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ --color=yes docs/make.jl --verbose
      after_success: skip
